### ISSUE TITLE
When deploying tunnel server， I encountered a parameter error.

### ISSUE THREAD

**Issue by XY-Yolanda** [alibaba/openyurt#117]
As described above，I met an error ， the pod log is：

Error: unknown flag: --server-count
Usage:
  Launch yurttunnel-server [flags]

Flags:
      --add_dir_header                   If true, adds the file directory to the header
      --alsologtostderr                  log to standard error as well as files
      --bind-address string              the ip address on which the yurttunnel-server will listen. (default "0.0.0.0")
      --cert-dns-names string            DNS names that will be added into server's certificate. (e.g., dns1,dns2)
      --cert-ips string                  IPs that will be added into server's certificate. (e.g., ip1,ip2)
      --egress-selector-enable           if the apiserver egress selector has been enabled.
      --enable-iptables                  if allow iptable manager to set the dnat rule. (default true)
  -h, --help                             help for Launch
      --iptables-sync-period int         the synchronization period of the iptable manager. (default 60)
      --kube-config string               path to the kubeconfig file.
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --log_file string                  If non-empty, use this log file
      --log_file_max_size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
      --skip_headers                     If true, avoid header prefixes in the log messages
      --skip_log_headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity
      --version                          print the version information of the yurttunnel-server.
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

F0916 07:28:18.939231       1 server.go:32] yurttunnel-server failed: unknown flag: --server-count

**Comment by charleszheng44** [comment]
@XY-Yolanda thanks for filing the issue. I just rebuilt and pushed the image `openyurt/yurt-tunnel-server:latest`. It should work now with the `server-count` command-line option.
