### ISSUE TITLE
Check state of node before run revert

### ISSUE THREAD

**Issue by vincent-pli** [alibaba/openyurt#125]
I think we should check the state of node(worker) to make sure it's `Ready` before run `revert`.
or will cause the worker node in a inconsistent state:
The label/annotation is removed but `yurthub` not removed, `kubelet` not reset, it will cause issue when try to run `convert` again.

**Comment by charleszheng44** [comment]
@vincent-pli that's a good point 👍 . Would you like to implement it?

**Comment by vincent-pli** [comment]
@charleszheng44 
Sure, I'm glad to take a try.

**Comment by charleszheng44** [comment]
Thx : ) Let us know if you have any questions.
