### ISSUE TITLE
[feature request] the  definition of NodePool and UnitedDeployment 

### ISSUE THREAD

**Issue by kadisi** [alibaba/openyurt#171]
**What would you like to be added**:

In the edge scenario, compute nodes have strong regional attributes. There may only be one WOker node in the same physical location, and there may also be multiple worker nodes in the same physical location. Therefore, from the work Node resource perspective of edge nodes, they need to be divided into different node pools (NodePool) to represent the same set of features. After dividing nodes pool, there will be a demand for application of grouping management, users need to be deployed application according to the unit, combined with the concept of node pool, to deploy applications on different nodes in the pool, pool dimensions at the nodes to expansion of application, upgrade, such as operation, at the same time, network access is also carried out in accordance with the node pool dimensions of network communication.

**Why is this needed**:

So we define `NodePool` and `UnitedDeployment` for both scenarios using Kubernetes CRD as the abstract

`NodePool`:

Nodes can be added and removed from the node pool.
Nodes within the node pool can be managed uniformly, such as label, annotation, and taints.

`UnitedDeployment`:
UnitedDeployment can use one of k8s Deployment, Daemonset, StatefulSet as a template for Deployment in a different node pool. At the same time, you can set the number of POD replicas deployed by different node pools

ref #124 

cc @huangyuqi @Fei-Guo @rambohe-ch @charleszheng44 

task list:

- [x] [add nodepool and uniteddeployment crd proposal ](https://github.com/alibaba/openyurt/pull/173)
- [x] [add yurt-app-manager api](https://github.com/alibaba/openyurt/pull/175)
- [x] [add yurt-app-manager nodepool controller add webhook](https://github.com/alibaba/openyurt/pull/178)
- [x] [add yurt-app-manager unitedeployment controller add webhook](https://github.com/alibaba/openyurt/pull/177)
- [x] [add makefile cmd for yurt-app-manager](https://github.com/alibaba/openyurt/pull/182)

**Comment by Fei-Guo** [comment]
Sounds great. Looking forward to them. By the way, is this a feature request? This should be proposal since you already implement them! :)

**Comment by kadisi** [comment]
> Sounds great. Looking forward to them. By the way, is this a feature request? This should be proposal since you already implement them! :)

ok @Fei-Guo  ref #173

**Comment by yixingjia** [comment]
Looking forward for the NodePool feature!  

By the way please also consider the follow scenario if possible in the future:

**Requirement**:

Workload(eg service) deployed on a node pool, it has basic HA requirement (let's put the shared storage issue aside first, just assume the service is stateless to make it simple), which mean when one node in the node pool failed, the workload can be automatically migrate to other healthy nodes.

**Scenario**:

Node pool lost connection with API server.

**Expectation:**

The auto migration should still works.

**Comment by ttzeng** [comment]
@kadisi would you please clarify, in your mind, what's the relationship between Yurt unit and the proposed NodePool? I could be wrong, but I have an impression they are interchangeable in terms of grouping nodes in a geolocation?

**Comment by Walnux** [comment]
In order to understand the feature clearly, please allow me to summarize the requirements of NodePools according to the above comments which are followed by my questions.
I will be appreciated if someone can correct the summary and answer my questions. :) 

### Requirement:
1. A bunch of nodes with the same attributes/features on the Edge side should be united into a group (NodePool) to be managed as a unit.  
Q1: What are the criteria to create a group(NodePool)? It is done automatically or manually? if manually who is in charge of it?
Q2: Does every Edge node belong to a specific group(NodePool)?

2. From Edge Computing work node resources perspective, the group(NodePool) should be used to represent the same set of attributes
Q1: Could we have a more detailed description of the work node resource as well as the same set of attributes/features? How to represent the attributes? It is great if an example can be provided.

3. Workload(Application) grouping management:  Edge computing workloads should be managed according to the group(NodePool) 
Q1: I think we need a more detailed description of what is " workload group management" and what are the sub-features of workload group management.  I list some below.

3.1 Workloads should be deployed in the scope of the nodes for the picked group(NodePool)
Q1: How to scheduler the workload to the Node of a specific group(NodePool), it is handled only by the scheduler on the control panel?
3.2 ReplicaSet is supported on the group(Nodepool)
Q1: How to handle Replicaset in the autonomous mode         

3.2 Autoscale, A/B testing can be implemented in the scope of the nodes for the picked group(NodePool).

3.3 Migrate workload to the healthy nodes within the group(NodePool). From @yixingjia 

4. Network Mode of the Group(NodePool)
Q1 Could we clarify the detail about "network access is also carried out in accordance with the node pool dimensions of network communication."
Can I call the feature as Group(Nodepool) Network Mode? It should be a very important concept in the scenario where Edge data must be limited within the Group(NodePool).

Other Suggestion
1. We might need to find a better name than "NodePool".
according to [wiki](https://en.wikipedia.org/wiki/Pool_(computer_science)) "Pool" in computing science means "a collection of resources that are kept ready to use, rather than acquired on use and released afterwards. " like "memory pool" and "thread pool". It looks like the nodes group has a lot of more means.

I feel to some degree, it is something like a "sub-cluster". maybe we can just call it "EdgeCluster". Or if you think "Cluster" is abused, "Bunch" is another option, since "Bunch" means a small "Cluster".
According to [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/bunch) It means a number of things of the same type fastened together or in a close group.

**Comment by kadisi** [comment]
#

> Looking forward for the NodePool feature!
> 
> By the way please also consider the follow scenario if possible in the future:
> 
> **Requirement**:
> 
> Workload(eg service) deployed on a node pool, it has basic HA requirement (let's put the shared storage issue aside first, just assume the service is stateless to make it simple), which mean when one node in the node pool failed, the workload can be automatically migrate to other healthy nodes.
> 
> **Scenario**:
> 
> Node pool lost connection with API server.
> 
> **Expectation:**
> 
> The auto migration should still works.

@yixingjia thanks for your advice。 This requires a simple scheduler in the NodePool that can do some simple scheduling when the entire NodePool is disconnected from the Apiserver.

**Comment by kadisi** [comment]
> @kadisi would you please clarify, in your mind, what's the relationship between Yurt unit and the proposed NodePool? I could be wrong, but I have an impression they are interchangeable in terms of grouping nodes in a geolocation?

@ttzeng sorry, I did not understand what you mean. Can you explain in detail？

**Comment by kadisi** [comment]
> ### Requirement Summary:
> 1. A bunch of nodes with the same attributes/features on the Edge side should be united into a group (NodePool) to be managed as a unit.
>    Q1: What are the criteria to create a group(NodePool)? It is done automatically or manually? if manually who is in charge of it?
>    Q2: Does every Edge node belong to a specific group(NodePool)?

A1:  Users can create node pools based on some commonalities of Node, not just limited to geographical distribution

A2: The user needs to manually create the node pool according to the actual scenario. The node pool is a CRD definition in k8s

A3: A node may not belong to any node pool



> 3. Workload(Application) grouping management:  Edge computing workloads should be managed according to the group(NodePool)
>    Q1: I think we need a more detailed description of what is " workload group management" and what are the sub-features of workload group management.  I list some below.
>    3.1. Workloads should be deployed in the scope of the nodes for the picked group(NodePool)
>    Q1: How to scheduler the workload to the Node of a specific group(NodePool), it is handled only by the scheduler on the control panel?

A1: We will define a `UnitedDeployment` k8s crd  to describe the workload. `UnitedDeployment` will define a template (such as k8s deployment), and also define a topology, which represents the NodePools to which the pod is deployed using this template. The controller will create a child k8s deployment according to each NodePool, and each child's deploymnet is responsible for deploying its own pod to the corresponding NodePool

>    3.3.  Autoscale, A/B testing can be implemented in the scope of the nodes for the picked group(NodePool).


> 4. Network Mode of the Group(NodePool)
>    Q1 Could we clarify the detail about "network access is also carried out in accordance with the node pool dimensions of network communication."
>    Can I call the feature as Group(Nodepool) Network Mode? It should be a very important concept in the scenario where Edge data must be constrained within the Group(NodePool).

A: ref https://kubernetes.io/docs/concepts/services-networking/service-topology/
 
> ### Other Suggestion
> **1. We might need to find a better name than "NodePool".**
> according to [wiki](https://en.wikipedia.org/wiki/Pool_(computer_science)) **"Pool"** in computing science means "a collection of resources that are kept ready to use, rather than acquired on use and released afterward. " like "memory pool" and "thread pool".
> It looks like "nodes group" is much more than a resource group. To some degree, it is something like a "sub-cluster".
> So maybe we can call it **"EdgeCluster"**. Or if you think "Cluster" is abused, **"Bunch"** is another option, "Bunch" is a small "Cluster".
> According to [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/bunch) "Bunch" means a number of things of the same type fastened together or in a close group. Isn't it good to describe "nodes group"? :)

A:  for `sub-cluster` and `EdgeCluster` It is more like a small k8s cluster， I think it’s different from the scene we described。 


@Walnux thank you very mush for your advice。

**Comment by ttzeng** [comment]
> @ttzeng sorry, I did not understand what you mean. Can you explain in detail？

@kadisi , would you please clarify what's the difference between the proposed NodePool and the coming Yurt Unit?

**Comment by Walnux** [comment]
> > Looking forward for the NodePool feature!
> > By the way please also consider the follow scenario if possible in the future:
> > **Requirement**:
> > Workload(eg service) deployed on a node pool, it has basic HA requirement (let's put the shared storage issue aside first, just assume the service is stateless to make it simple), which mean when one node in the node pool failed, the workload can be automatically migrate to other healthy nodes.
> > **Scenario**:
> > Node pool lost connection with API server.
> > **Expectation:**
> > The auto migration should still works.
> 
> @yixingjia thanks for your advice。 This requires a simple scheduler in the NodePool that can do some simple scheduling when the entire NodePool is disconnected from the Apiserver.

@kadisi It means there will be a scheduler for each NodePool?  The other relevant question is what do we need to change the behavior of the scheduler in the control panel, which will take NodePool as a unit to deploy pods or it still handles all the nodes in the NodePools? Thanks!

**Comment by Walnux** [comment]
> > ### Requirement Summary:
> > 
> > 1. A bunch of nodes with the same attributes/features on the Edge side should be united into a group (NodePool) to be managed as a unit.
> >    Q1: What are the criteria to create a group(NodePool)? It is done automatically or manually? if manually who is in charge of it?
> >    Q2: Does every Edge node belong to a specific group(NodePool)?
> 
> A1: Users can create node pools based on some commonalities of Node, not just limited to geographical distribution
> 
> A2: The user needs to manually create the node pool according to the actual scenario. The node pool is a CRD definition in k8s
> 
> A3: A node may not belong to any node pool
> 
> > 1. Workload(Application) grouping management:  Edge computing workloads should be managed according to the group(NodePool)
> >    Q1: I think we need a more detailed description of what is " workload group management" and what are the sub-features of workload group management.  I list some below.
> >    3.1. Workloads should be deployed in the scope of the nodes for the picked group(NodePool)
> >    Q1: How to scheduler the workload to the Node of a specific group(NodePool), it is handled only by the scheduler on the control panel?
> 
> A1: We will define a `UnitedDeployment` k8s crd to describe the workload. `UnitedDeployment` will define a template (such as k8s deployment), and also define a topology, which represents the NodePools to which the pod is deployed using this template. The controller will create a child k8s deployment according to each NodePool, and each child's deploymnet is responsible for deploying its own pod to the corresponding NodePool
> 
> > 3.3.  Autoscale, A/B testing can be implemented in the scope of the nodes for the picked group(NodePool).
> 
> > 1. Network Mode of the Group(NodePool)
> >    Q1 Could we clarify the detail about "network access is also carried out in accordance with the node pool dimensions of network communication."
> >    Can I call the feature as Group(Nodepool) Network Mode? It should be a very important concept in the scenario where Edge data must be constrained within the Group(NodePool).
> 
> A: ref https://kubernetes.io/docs/concepts/services-networking/service-topology/
> 
> > ### Other Suggestion
> > **1. We might need to find a better name than "NodePool".**
> > according to [wiki](https://en.wikipedia.org/wiki/Pool_(computer_science)) **"Pool"** in computing science means "a collection of resources that are kept ready to use, rather than acquired on use and released afterward. " like "memory pool" and "thread pool".
> > It looks like "nodes group" is much more than a resource group. To some degree, it is something like a "sub-cluster".
> > So maybe we can call it **"EdgeCluster"**. Or if you think "Cluster" is abused, **"Bunch"** is another option, "Bunch" is a small "Cluster".
> > According to [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/bunch) "Bunch" means a number of things of the same type fastened together or in a close group. Isn't it good to describe "nodes group"? :)
> 
> A: for `sub-cluster` and `EdgeCluster` It is more like a small k8s cluster， I think it’s different from the scene we described。
> 
> @Walnux thank you very mush for your advice。

@kadisi very clear answer, thanks! It is great if we can record all these clearfication into a docuement. :)

**Comment by kadisi** [comment]
- [ ] [add nodepool and uniteddeployment crd proposal ](https://github.com/alibaba/openyurt/pull/173)
- [ ] [add yurtunit-manager api](https://github.com/alibaba/openyurt/pull/175)
- [ ] add yurtunit-manager nodepool controller add webhook
- [ ] add yurtunit-manager unitedeployment controller add webhook
- [ ] add makefile cmd for yurtunit-manager
