### ISSUE TITLE
[feature request]Add commands so that single node could convert to a standard Kubernetes node or an OpenYurt edgenode

### ISSUE THREAD

**Issue by Peeknut** [alibaba/openyurt#190]
**What would you like to be added**:
Add commands, such as `yurtctl convert edgenode ` and `yurtctl revert edgenode` , so that single node could use these commands to  convert a standard Kubernetes node to an OpenYurt edgenode or revert an OpenYurt edgenode.

**Why is this needed**:
The commands `yurtctl convert`、`yurtctl revert` will convert all edge nodes to OpenYurt cluster or Kubernetes cluster. If a new edge node is added after conversion, there are no corresponding commands to convert it to an OpenYurt edgenode or a Kubernetes node. We can only use commands `yurtctl convert`、`yurtctl revert` again to convert all edge nodes, which may cause errors and be low efficiency. So commands are needed to allow a single node to convert and revert.

**Comment by Peeknut** [comment]
@rambohe-ch @GsssC

**Comment by huangyuqi** [comment]
@Peeknut 
Actually, if the node joins the cluster as before, it will still be a stand node ,not a yurt node; 
Base on the pattern of node joining.
The ability of joining node with yurt type will open source soon ;

**Comment by GsssC** [comment]
Then we can remove [the servant bash script](https://github.com/alibaba/openyurt/blob/master/config/yurtctl-servant/setup_edgenode) then use `yurtctl convert edgenode`.

**Comment by huangyuqi** [comment]
@zyjhtangtang Would you mind bringing a proposal about joining a node in 'yurt' way?

**Comment by rambohe-ch** [comment]
> @Peeknut
> Actually, if the node joins the cluster as before, it will still be a stand node ,not a yurt node; Base on the pattern of node joining. We can bring out a command as 'yurtctl convert node xxx' or 'yurtctl revert node xxx' .
> BTW, The ability of joining node with yurt type will opensource soon ;

i think that node join feature and one node convert feature are different. because when user wants to use a customized tool to join node,  node convert feature maybe needed.

**Comment by rambohe-ch** [comment]
> Then we can remove [the servant bash script](https://github.com/alibaba/openyurt/blob/master/config/yurtctl-servant/setup_edgenode) instead of using `yurtctl convert edgenode`.
@GsssC  yeah, robustness of servant bash script is not so good, it is a good idea to use `golang command` to refactor it.
@Peeknut would you refactor the node convert/revert feature by golang?

**Comment by Peeknut** [comment]
> > Then we can remove [the servant bash script](https://github.com/alibaba/openyurt/blob/master/config/yurtctl-servant/setup_edgenode) instead of using `yurtctl convert edgenode`.
> 
> @GsssC yeah, robustness of servant bash script is not so good, it is a good idea to use `golang command` to refactor it.
> @Peeknut would you refactor the node convert/revert feature by golang?

ok

**Comment by Walnux** [comment]
I think this request is reasonable. And we do need a standard way (or feature) for the user to "join the node into the clusters". :+1:
