### ISSUE TITLE
[feature request] Command convert of yurtctl support param for kubelet service kubeadm conf

### ISSUE THREAD

**Issue by liangyuanpeng** [alibaba/openyurt#203]
**What would you like to be added**:
Command convert of yurtctl support param for kubelet service kubeadm conf

**Why is this needed**:
In centos, `10-kubeadm.conf` save in `/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf` and yurtctl convert use `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` by default . 

I want to solve this problem And i have a question about this param name->Do you think the name `kubelet-service-kubeadm-conf-path` will be too long? Thanks any !

**Comment by charleszheng44** [comment]
+1 for this feature. I think we can have a shorter command-line option name, like `kubeadm-conf-path`, and a detailed description, like "The path to the kubeadm configuration file that is used by the kubelet service to join the cluster. N.B. the path on different Linux distro may vary"

**Comment by liangyuanpeng** [comment]
> +1 for this feature. I think we can have a shorter command-line option name, like `kubeadm-conf-path`, and a detailed description, like "The path to the kubeadm configuration file that is used by the kubelet service to join the cluster. N.B. the path on different Linux distro may vary"

Sure, I found the `kubeadm_config_path` in `constants.go`  already in use.

**Comment by rambohe-ch** [comment]
@liangyuanpeng I think it's a good feature. and the parameter of kubelet service conf path does not only for kubeadm tool,  other tools may also need this parameter. so how about `kubelet-service-conf-path` for parameter name? @charleszheng44

**Comment by liangyuanpeng** [comment]
> @liangyuanpeng I think it's a good feature. and the parameter of kubelet service conf path does not only for kubeadm tool, other tools may also need this parameter. so how about `kubelet-service-conf-path` for parameter name? @charleszheng44

I'm not sure if `kubea-conf-path` will cause ambiguity, maybe it will be make people think of `kubeadm init config file ` and  `kubelet-service-conf-path` seem like not related to kubeadm. I can think of another name is `ks-kubeadm-conf-path`. (ks->kubelet service)

I have developed functional content, i will create a PR when we decided on the name! Thanks for your reply.

**Comment by charleszheng44** [comment]
> @liangyuanpeng I think it's a good feature. and the parameter of kubelet service conf path does not only for kubeadm tool, other tools may also need this parameter. so how about `kubelet-service-conf-path` for parameter name? @charleszheng44

Which tool would also use the `10-kubeadm.conf`? I thought we revise the `10-kubeadm.conf` only for pointing to the kubelet.conf associated to the yurthub.

**Comment by rambohe-ch** [comment]
> > @liangyuanpeng I think it's a good feature. and the parameter of kubelet service conf path does not only for kubeadm tool, other tools may also need this parameter. so how about `kubelet-service-conf-path` for parameter name? @charleszheng44
> 
> Which tool would also use the `10-kubeadm.conf`? I thought we revise the `10-kubeadm.conf` only for pointing to the kubelet.conf associated to the yurthub.

@charleszheng44 @liangyuanpeng `10-kubeadm.conf` is system service conf file for kubelet component, and now other tool(like minikube) may also make up the same name kubelet service file(`10-kubeadm.conf`), so i think it's good definition without `kubeadm` word in new parameter.  then `kubelet-service-conf-path` maybe a good selection.

**Comment by rambohe-ch** [comment]
> > @liangyuanpeng I think it's a good feature. and the parameter of kubelet service conf path does not only for kubeadm tool, other tools may also need this parameter. so how about `kubelet-service-conf-path` for parameter name? @charleszheng44
> 
> I'm not sure if `kubea-conf-path` will cause ambiguity, maybe it will be make people think of `kubeadm init config file ` and `kubelet-service-conf-path` seem like not related to kubeadm. I can think of another name is `ks-kubeadm-conf-path`. (ks->kubelet service)
> 
> I have developed functional content, i will create a PR when we decided on the name! Thanks for your reply.

@liangyuanpeng thank you for your quick response, and @Peeknut has [another pr](https://github.com/alibaba/openyurt/pull/206) that has revised node convert and revert, so your pr may need to rebase it when pr is creating.

**Comment by rambohe-ch** [comment]
@charleszheng44 @liangyuanpeng by the way, yurtctl maybe need some statement like only support to convert or revert node that kubelet is managed by system service.  if run kubelet directly by binary file, yurtctl may not support it.

**Comment by rambohe-ch** [comment]
> Thanks for your reply and i just really used `kubeadm-conf-path` for param name and it's satisfying enough.
> 
ok, `kubeadm-conf-path` maybe the same meaning as kubelet service conf path, so `kubeadm-conf-path` can be accepted, and please add `The path of kubelet service conf` for `kubeadm-conf-path` usage.
