### ISSUE TITLE
[feature request] yurtctl cluster-info subcommand that list edge/cloud nodes

### ISSUE THREAD

**Issue by neo502721** [alibaba/openyurt#207]
**What would you like to be added**:
Add a yurtctl subcommand cluster-info, that list edge and cloud nodes.
Actually, I saw this in the [https://openyurt.io/zh-cn/docs/todo.html](url) todo list.
And I have finished the code development. The simple effect is as shown below. That's list edge/cloud nodes filter by k8s node label. 
I will create a pr later, thanks!

![image](https://user-images.githubusercontent.com/19708079/105967623-05f79b80-60c1-11eb-88dd-7b2d6497a27d.png)

**Why is this needed**:
Belongs to the openyurt.io todo list.

**Comment by rambohe-ch** [comment]
@neo502721 Very much appreciate for your issue, and pr for yurtctl subcommand cluster-info is welcome.
