### ISSUE TITLE
[Question]Run yurthub failed

### ISSUE THREAD

**Issue by suojy** [alibaba/openyurt#215]
**What happened**:
I followed the manually-setup guide to set up yurthub.  Error info is failed to load ca file(/etc/kubernetes/pki/ca.crt) but that file does exist.  I don't know if there's other reasons. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: latest
- Kubernetes version (use `kubectl version`): 1.14
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

logs of yurthub
yurthub version: projectinfo.Info{GitVersion:"v0.3.0", GitCommit:"4adbba4", BuildDate:"2021-01-08T07:10:31Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
I0204 09:23:35.595908       1 start.go:43] FLAG: --add_dir_header="false"
I0204 09:23:35.596110       1 start.go:43] FLAG: --alsologtostderr="false"
I0204 09:23:35.596224       1 start.go:43] FLAG: --bind-address="127.0.0.1"
I0204 09:23:35.596339       1 start.go:43] FLAG: --cert-mgr-mode="kubelet"
I0204 09:23:35.596455       1 start.go:43] FLAG: --gc-frequency="120"
I0204 09:23:35.596544       1 start.go:43] FLAG: --heartbeat-failed-retry="3"
I0204 09:23:35.596618       1 start.go:43] FLAG: --heartbeat-healthy-threshold="2"
I0204 09:23:35.597332       1 start.go:43] FLAG: --heartbeat-timeout-seconds="2"
I0204 09:23:35.597919       1 start.go:43] FLAG: --help="false"
I0204 09:23:35.598013       1 start.go:43] FLAG: --join-token=""
I0204 09:23:35.598109       1 start.go:43] FLAG: --lb-mode="rr"
I0204 09:23:35.598200       1 start.go:43] FLAG: --log-flush-frequency="5s"
I0204 09:23:35.598322       1 start.go:43] FLAG: --log_backtrace_at=":0"
I0204 09:23:35.598478       1 start.go:43] FLAG: --log_dir=""
I0204 09:23:35.598585       1 start.go:43] FLAG: --log_file=""
I0204 09:23:35.598704       1 start.go:43] FLAG: --log_file_max_size="1800"
I0204 09:23:35.598794       1 start.go:43] FLAG: --logtostderr="true"
I0204 09:23:35.598867       1 start.go:43] FLAG: --max-requests-in-flight="250"
I0204 09:23:35.598934       1 start.go:43] FLAG: --node-name="slave1"
I0204 09:23:35.599024       1 start.go:43] FLAG: --root-dir="/var/lib/yurthub"
I0204 09:23:35.599096       1 start.go:43] FLAG: --serve-port="10261"
I0204 09:23:35.599108       1 start.go:43] FLAG: --server-addr="https://192.168.0.77:6443"
I0204 09:23:35.599113       1 start.go:43] FLAG: --skip_headers="false"
I0204 09:23:35.599118       1 start.go:43] FLAG: --skip_log_headers="false"
I0204 09:23:35.599122       1 start.go:43] FLAG: --stderrthreshold="2"
I0204 09:23:35.599125       1 start.go:43] FLAG: --v="2"
I0204 09:23:35.599129       1 start.go:43] FLAG: --version="false"
I0204 09:23:35.599134       1 start.go:43] FLAG: --vmodule=""
I0204 09:23:35.599282       1 config.go:79] yurthub would connect remote servers: https://192.168.0.77:6443
I0204 09:23:35.599304       1 start.go:53] yurthub cfg: &config.YurtHubConfiguration{LBMode:"rr", RemoteServers:[]*url.URL{(*url.URL)(0xc000592380)}, YurtHubHost:"127.0.0.1", YurtHubPort:10261, GCFrequency:120, CertMgrMode:"kubelet", NodeName:"slave1", HeartbeatFailedRetry:3, HeartbeatHealthyThreshold:2, HeartbeatTimeoutSeconds:2, MaxRequestInFlight:250, JoinToken:"", RootDir:"/var/lib/yurthub"}
I0204 09:23:35.599354       1 start.go:68] 1. new transport manager for healthz client
I0204 09:23:35.599390       1 start.go:76] 2. create health checker for remote servers 
I0204 09:23:35.604233       1 connrotation.go:140] create a connection from 192.168.0.72:52232 to 192.168.0.77:6443, total 1 connections in transport manager dialer
I0204 09:23:35.612770       1 start.go:84] 3. init cert initializer
I0204 09:23:35.612790       1 start.go:88] 4. register cert managers
I0204 09:23:35.612798       1 certificate.go:61] Registered certificate manager kubelet
I0204 09:23:35.612809       1 certificate.go:61] Registered certificate manager hubself
I0204 09:23:35.612815       1 start.go:94] 5. create cert manager with kubelet mode
I0204 09:23:35.612839       1 cert_mgr.go:86] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
I0204 09:23:35.613141       1 start.go:102] 6. update transport manager
I0204 09:23:35.613151       1 transport.go:99] use /etc/kubernetes/pki/ca.crt ca cert file to access remote server
E0204 09:23:35.613164       1 transport.go:103] could not get tls config when update transport, failed to load ca file(/etc/kubernetes/pki/ca.crt)
E0204 09:23:35.613172       1 start.go:105] could not update transport manager, failed to load ca file(/etc/kubernetes/pki/ca.crt)
F0204 09:23:35.613178       1 start.go:56] run yurthub failed, failed to load ca file(/etc/kubernetes/pki/ca.crt)

**Comment by rambohe-ch** [comment]
@suojy Thank you for filing the issue.
would you output the whole yurthub yaml file? maybe the path of yurthub.yaml is `/etc/kubernetes/manifests/yurthub.yaml`

**Comment by suojy** [comment]
I forgot to change the host path.  It is running now.
Thanks for your help. (●'◡'●)
