### ISSUE TITLE
Minimal hardware requirement for openyurt node device?

### ISSUE THREAD

**Issue by applea9** [alibaba/openyurt#216]
If we want to use openyurt in the IOT scenario and manage the edge device such as raspberry pi, do we have any guildline or benchmark that introduce the minimal hardware requirement for the edge device? The hardware requirement could be arch, memory, etc.

**Comment by rambohe-ch** [comment]
@applea9 Thank you for filing issue to discuss hardware requirement for OpenYurt.
I am so sorry that OpenYurt is lack of doc or tutorial of hardware requirement currently, and I think we can prepare it in next release.

At the same time I can provide the information that raspberry pi4 can work OpenYurt well. you can get the details from the link: https://mp.weixin.qq.com/s/Anr8UhTaNe3FCnKKfKoXNQ

**Comment by applea9** [comment]
thanks
