### ISSUE TITLE
yaml error

### ISSUE THREAD

**Issue by huskar-t** [alibaba/openyurt#31]
there's an error in
/config/setup/yurthub.yaml 
line 12
Can this quality really be used in industry？

**Comment by idevz** [comment]
I think this is not an error, it's an placeholder for your `__pki_path__`

**Comment by huangyuqi** [comment]
please use the admin tool 'yurtctl' to install.  The placeholder also can be replaced manually @huskar-t

**Comment by huskar-t** [comment]
Well, i didn't study the code carefully
