### ISSUE TITLE
What real thing the function kubeutil.RunServantJob() do

### ISSUE THREAD

**Issue by Icedroid** [alibaba/openyurt#32]
The image openyurt/yurtctl-servant source code will be open source?
deploy yurt-hub and reset the kubelet service  in a kubernetes job use the openyurt/yurtctl-servant:latest image. But I can't know the job change the things of kubelet.

**Comment by charleszheng44** [comment]
@Icedroid Yes. The source code of yurtctl-servant can be found at `config/yurtctl-servant`.

**Comment by Icedroid** [comment]
ServantJobTemplate:
   ```
command:
        - /bin/sh
        - -c
  args:  
      - "sed -i 's|__kubernetes_service_host__|$(KUBERNETES_SERVICE_HOST)|g;s|__kubernetes_service_port_https__|$(KUBERNETES_SERVICE_PORT_HTTPS)|g;s|__node_name__|$(NODE_NAME)|g' /var/lib/openyurt/setup_edgenode && cp /var/lib/openyurt/setup_edgenode /tmp && nsenter -t 1 -m -u -n -i /var/tmp/setup_edgenode {{.action}} {{.provider}}"
```

 /var/tmp/setup_edgenode  shouw be /tmp/setup_edgenode ?
