### ISSUE TITLE
yurt-cntroller-manager's log show an error: error retrieving resource lock kube-system/yurt-controller-manager

### ISSUE THREAD

**Issue by xmwilldo** [alibaba/openyurt#43]
I follow the GitHub Manually Setup doc, but I find a error in yurt-controller-manager:
> error retrieving resource lock kube-system/yurt-controller-manager: leases.coordination.k8s.io "yurt-controller-manager" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"

and I think the yurt-controller-manager is not working, because when I disconnect the yurthub on edgenode, the edgenode's status is still ready.

**Comment by rambohe-ch** [comment]
@xmwilldo maybe rbac setting step is missed in manually setup doc, you can exec the following command to add permission for yurt-controller-manager.
`kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default`
