### ISSUE TITLE
the pod 'yurtctl-servant-convert' always becomes 'CrashLoopBackOff' when i convert minikube to openyurt cluster

### ISSUE THREAD

**Issue by XY-Yolanda** [alibaba/openyurt#44]
i got this error message when i excuted this command  ` _output/bin/yurtctl convert --provider minikube`
![image](https://user-images.githubusercontent.com/13092534/84139558-af324880-aa82-11ea-80d4-5e19af8a4d1f.png)
the status  of the pod became 'CrashLoopBackOff' and there was no error log
![image](https://user-images.githubusercontent.com/13092534/84139701-eef93000-aa82-11ea-8199-24ea2a091253.png)

Thanks for ur help!

**Comment by charleszheng44** [comment]
Thanks for filing the issue. May I know your kubernetes version, and node OS information? Also could you log in to the node, and check the log of the servant-pod through container runtime (e.g. docker log)? Thanks
