### ISSUE TITLE
Nothing output use incorrect "provider"

### ISSUE THREAD

**Issue by vincent-pli** [alibaba/openyurt#46]
I took a try with `yurtctl` on my local `kubeadm` env, I'm not notice the validate `provider` should be `minikube` or `ack`, I omit it, then I get nothing after run the command.

BTW, will we not support `kubeadm` or `kind` or others?

**Comment by xmwilldo** [comment]
It's not supported now. if you init k8s cluster by kubeadm,I suggest you use manual installation

**Comment by xmwilldo** [comment]
> I took a try with `yurtctl` on my local `kubeadm` env, I'm not notice the validate `provider` should be `minikube` or `ack`, I omit it, then I get nothing after run the command.
> 
> BTW, will we not support `kubeadm` or `kind` or others?

It's not supported now. if you init k8s cluster by kubeadm,I suggest you use manual installation

**Comment by charleszheng44** [comment]
> I took a try with `yurtctl` on my local `kubeadm` env, I'm not notice the validate `provider` should be `minikube` or `ack`, I omit it, then I get nothing after run the command.
> 
> BTW, will we not support `kubeadm` or `kind` or others?

If you don't specify a provider,  `ack` will be used as the default. During the runtime, there is no indicator that can verify the correctness of the provider, so it dependents on the user to specify the correct provider. However, when converting the cluster, the main difference between different providers is the pki path(e.g., `/etc/kubernetes/pki` or `/var/lib/minikube/cert`).  If the target Kubernetes cluster is deployed by kubeadm, you can try to use the `ack` mode, it should work just fine. 
In the future, we will support kubeadm and kind.

**Comment by vincent-pli** [comment]
@charleszheng44 @xmwilldo thanks for quick replies.

But I still get nothing..., any thrown exception/error will be helpful.
```
root@nisuses1:~/go/src/github.com/alibaba/openyurt# kubectl get node
NAME                    STATUS     ROLES    AGE    VERSION
khans1.fyre.ibm.com     NotReady   <none>   104d   v1.17.3
nisuses1.fyre.ibm.com   Ready      master   105d   v1.17.3
root@nisuses1:~/go/src/github.com/alibaba/openyurt#  _output/bin/yurtctl convert --provider ack --cloud-nodes nisuses1.fyre.ibm.com
root@nisuses1:~/go/src/github.com/alibaba/openyurt#
```

**Comment by vincent-pli** [comment]
@charleszheng44 
The `help` works:
```
root@nisuses1:~/go/src/github.com/alibaba/openyurt# _output/bin/yurtctl convert -h
Converts the kubernetes cluster to a yurt cluster

Usage:
  yurtctl convert -c CLOUDNODES [flags]

Flags:
  -c, --cloud-nodes string                     The list of cloud nodes.(e.g. -c cloudnode1,cloudnode2)
  -h, --help                                   help for convert
  -p, --provider string                        The provider of the original Kubernetes cluster. (default "ack")
      --yurt-controller-manager-image string   The yurt-controller-manager image. (default "openyurt/yurt-controller-manager:latest")
      --yurtctl-servant-image string           The yurtctl-servant image. (default "openyurt/yurtctl-servant:latest")
      --yurthub-image string                   The yurthub image. (default "openyurt/yurthub:latest")

Global Flags:
      --kubeconfig string   The path to the kubeconfig file
```

**Comment by charleszheng44** [comment]
@vincent-pli do you mind checking out this branch https://github.com/charleszheng44/openyurt/tree/detailed-log, and try it again with the command `_output/bin/yurtctl convert -v 4 --provider ack --cloud-nodes nisuses1.fyre.ibm.com `? I have added more logs in this branch.

**Comment by vincent-pli** [comment]
@charleszheng44 
```
root@nisuses1:~/go/src/github.com/alibaba/openyurt# _output/bin/yurtctl convert -v 4 --provider ack --cloud-nodes nisuses1.fyre.ibm.com
I0611 00:18:37.551490   27606 convert.go:109] cloud nodes are: [nisuses1.fyre.ibm.com]
I0611 00:18:37.551629   27606 convert.go:116] provider is: ack
I0611 00:18:37.560518   27606 convert.go:141] successfully generate the clientset
I0611 00:18:37.560571   27606 convert.go:74] successfully complete the convert option
I0611 00:18:37.560598   27606 convert.go:78] convert option is valid
```

**Comment by charleszheng44** [comment]
@vincent-pli I think I have found the bug. Could you pull the branch and try the command again?

**Comment by vincent-pli** [comment]
ha, interesting, v1.17.x not support? do we have this in document?
```
root@nisuses1:~/go/src/github.com/alibaba/openyurt# _output/bin/yurtctl convert -v 4 --provider ack --cloud-nodes nisuses1.fyre.ibm.com
I0612 00:32:33.702802    5261 convert.go:160] successfully acquire the lock
F0612 00:32:33.733862    5261 convert.go:78] fail to convert kubernetes to yurt: server version(1.17) is not supported, valid server versions are [1.12 1.12+ 1.13 1.13+ 1.14 1.14+ 1.18]
root@nisuses1:~/go/src/github.com/alibaba/openyurt# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by charleszheng44** [comment]
Currently, we only support 1.12-1.14. It should work with higher versions(1.15- 1.18), but we have not officially tested yet. If you would like to play around with 1.17, you can manually add it as the supported versions by appending "1.17" to the variable `ValidServerVersions` in `pkg/yurtctl/util/kubernetes/util.go`, and recompile the yurtctl.
