### ISSUE TITLE
Forbidden error in yurt-controller-manager

### ISSUE THREAD

**Issue by vincent-pli** [alibaba/openyurt#52]
I saw permission forbidden error in `kube-system/yurt-controller-manager`:
```
E0615 08:50:17.179354       1 leaderelection.go:306] error retrieving resource lock kube-system/yurt-controller-manager: leases.coordination.k8s.io "yurt-controller-manager" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

BTW, I test `yurtctl` on my kubeadm env with k8s version v1.17.3, I think you can add the version to `pkg/yurtctl/util/kubernetes/util.go`, 👍

**Comment by rambohe-ch** [comment]
@vincent-pli 
maybe rbac setting step is missed, you can exec the following command to add permission for yurt-controller-manager.
`kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default`

@charleszheng44 maybe we need to add rabc setting in yurtctl

**Comment by vincent-pli** [comment]
@rambohe-ch 
It's exactly what I did, I mean we need add the RBAC to the guide.

**Comment by charleszheng44** [comment]
@vincent-pli good to know yurtctl works to 1.17.

**Comment by vincent-pli** [comment]
@charleszheng44 
I made the cluster with `kubeadm` manually.
```
root@nisuses1:~/tekton# kubectl auth can-i get lease --as=system:serviceaccount:kube-system:default -n kube-system
no
```

**Comment by charleszheng44** [comment]
@vincent-pli Thanks for letting me know. I will make the `yurtctl` to add the permission to the `serviceaccount:kube-system:default`, if it is not granted.

**Comment by vincent-pli** [comment]
@charleszheng44 thanks
