### ISSUE TITLE
请问Openyurt能实现云边协同嘛

### ISSUE THREAD

**Issue by Caixiaomeng** [alibaba/openyurt#55]
我是想在阿里云ECS上部署为master节点，然后本地虚拟机作为worker节点，然后通信==

**Comment by charleszheng44** [comment]
得保证 ecs 节点上的 master 能被外网访问，可以考虑购买一个 SLB 绑定 EIP。之后可以尝试手动配置流程，或者尝试将本地虚拟机先以正常节点形式加入到集群，再使用yurtctl convert

**Comment by rambohe-ch** [comment]
> 我是想在阿里云ECS上部署为master节点，然后本地虚拟机作为worker节点，然后通信==

如果在阿里云ECS上部署master节点，建议可以直接使用阿里云容器服务的边缘托管集群，边缘托管集群是OpenYurt的商业化产品。产品链接: cs.console.aliyun.com

**Comment by Fei-Guo** [comment]
The issue has been addressed. Feel free to reopen it if more discussions are needed.
