### ISSUE TITLE
edge node cannot be properly set if `--bootstrap-kubeconfig` is used by kubelet

### ISSUE THREAD

**Issue by charleszheng44** [alibaba/openyurt#56]
Several users have reported that if kubelet of edge nodes using `--bootstrap-kubeconfig`, the `/var/lib/openyurt/kubelet.conf` will keep being reset. This is because `/var/lib/openyurt/kubelet.conf` is created based on `/etc/kubernetes/kubelet.conf`, while `/etc/kubernetes/kubelet.conf` will be reset if kubelet is relying on the `--bootstrap-kubeconfig`.

**Comment by Fei-Guo** [comment]
This should be fixed by #76. Feel free to reopen the issue if the problem still exists.
