### ISSUE TITLE
support kubernetes v1.16.x version

### ISSUE THREAD

**Issue by rambohe-ch** [alibaba/openyurt#62]
in order to support k8s v1.16.x version in openyurt, we need to improve the following associated components
  - yurthub:  bookmark process
  - yurt-controller-manager: following kube-controller-manager of k8s v1.16.x version
  - yurtctl: convert v1.16.x k8s to openyurt

**Comment by rambohe-ch** [comment]
@charleszheng44 i will add a pr to slove the adaption for yurthub and yurt-controller-manager, and would you take care of the adaption of yurtctl?

**Comment by charleszheng44** [comment]
> @charleszheng44 i will add a pr to slove the adaption for yurthub and yurt-controller-manager, and would you take care of the adaption of yurtctl?

Yes. just added 1.16 + as a valid version. see #64
