### ISSUE TITLE
请问openyurt支持边缘设备管理吗 

### ISSUE THREAD

**Issue by mocunAce** [alibaba/openyurt#68]
如果支持边缘设备管理，支持哪些通信协议？
部署边缘端最小的资源要求是多少？
最多支持管理多少的边缘节点个数

**Comment by rambohe-ch** [comment]
1. 边缘设备管理属于IOT场景范畴，边缘设备管理不和OpenYurt绑定，只是OpenYurt的其中一个使用场景。
2. 目前已经有商业产品以OpenYurt为底座，支持IOT场景。具体可以参照[物联网边缘计算](https://help.aliyun.com/document_detail/85155.html?spm=5176.cniotedge.0.0.624b61efV5LjUs)

**Comment by rambohe-ch** [comment]
@mocunAce To support OpenYurt in github, please use English for further communication

**Comment by mocunAce** [comment]
@rambohe-ch Thank you for your reply.
Edge device management is done through the application of edge nodes, right?

**Comment by rambohe-ch** [comment]
> @rambohe-ch Thank you for your reply.
> Edge device management is done through the application of edge nodes, right?

yes, containerized applications that run on edge nodes will cover device management.

**Comment by Fei-Guo** [comment]
This issue has been addressed. Feel free to reopen it if more details need to be discussed.
