### ISSUE TITLE
project can not compile

### ISSUE THREAD

**Issue by tiny1990** [alibaba/openyurt#8]
run `make` error.
```
go: finding module for package golang.org/x/oauth2
go: finding module for package github.com/Azure/go-ansiterm/winterm
go: finding module for package github.com/Azure/go-ansiterm
go: finding module for package github.com/Sirupsen/logrus
go: found github.com/Azure/go-ansiterm/winterm in github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
go: found github.com/Sirupsen/logrus in github.com/Sirupsen/logrus v1.6.0
go: github.com/alibaba/openyurt/cmd/yurt-controller-manager/app imports
        k8s.io/apiserver/pkg/util/term imports
        github.com/docker/docker/pkg/term imports
        github.com/docker/docker/pkg/term/windows imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```

**Comment by Fei-Guo** [comment]
The repo is still under construction, bear us with any build failures.

**Comment by rambohe-ch** [comment]
@tiny1990 what's version of your go that used for compile.
and can you try compile again after clear up go mod file($GOPATH/pkg)

by the way, i haven't come across this compile error.

**Comment by tiny1990** [comment]
@rambohe-ch  build with golang 1.14

**Comment by ruster-cn** [comment]
github.com/Sirupsen/logrus is the old path, the author suggest ["Anything using it should be updated to import and require github.com/sirupsen/logrus." ](https://github.com/sirupsen/logrus/issues/1041). I think we can change as github.com/sirupsen/logrus, because this change can run in go version >= 1.13.

**Comment by tiny1990** [comment]
@rambohe-ch 
in order to isolate host GOPATH , build in container.
if i run command `docker run -it  --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.13 go mod vendor`  
logs.  
```log
go: github.com/alibaba/openyurt/cmd/yurt-controller-manager/app imports
	k8s.io/apiserver/pkg/util/term imports
	github.com/docker/docker/pkg/term imports
	github.com/docker/docker/pkg/term/windows imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
```
so we need replace `github.com/Sirupsen/logrus` => github.com/sirupsen/logrus

and run command `docker run -it  --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.13 make`. 
logs   
```log
build github.com/alibaba/openyurt/cmd/yurtctl: cannot load github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.4.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
```
so. i think we need replace two package  

`github.com/googleapis/gnostic` and `github.com/Sirupsen/logrus`

**Comment by charleszheng44** [comment]
@tiny1990 thanks for filing the issue. I have changed the `github.com/googleapis/gnostic` to v0.3.1. It should work now.
