### ISSUE TITLE
change label "alibabacloud.com/xxxx" into a more common name? 

### ISSUE THREAD

**Issue by feilengcui008** [alibaba/openyurt#81]
I notice there are several labels prefixed with the name "alibabacloud.com", e.g. "alibabacloud.com/is-edge-worker", maybe something like "openyurt.com/xxx" is better.

**Comment by rambohe-ch** [comment]
@feilengcui008 thank you for filing the issue.
@charleszheng44 maybe we can fix these specific labels by using compile settings. and modify alibabacloud.com prefix to openyurt.io
