### ISSUE TITLE
failed to delete the configMap(yurtctl-lock)

### ISSUE THREAD

**Issue by cfw11** [alibaba/openyurt#84]
### ENV
`k8s version`: v1.16.12  
`openyurt version`: don't find "-v" or "version", sync code from github on 2020.7.30  
`work node`: centos7,   kenel:3.10.0-957.1.3.el7.x86_64,   docker:17.12.1-ce
`master node`: ubuntu-16.04,   kenel:4.15.0-45-generic,  docker:19.03.6

### DESC  
convert a k8s cluster to openyurt cluster, wait a minutes....., use Ctrl+C to exit.   
After that excute any Cmd has such error:
![image](https://user-images.githubusercontent.com/34058899/88924609-15c72c00-d2a6-11ea-8dfc-70627f060ed1.png)  
by the way, the configmap which name is yurtctl-lock can't be deleted.  api-server is normal.

**Comment by charleszheng44** [comment]
@cfw11 thanks for filing the issue. The reason `configmap/yurtctl-lock` can't be deleted is that after hitting `ctrl+c`, the `yurtctl convert` is interrupted, while the `configmap/yurtctl-lock` is not released. We will add a timeout mechanism to the lock.  For now, could you try to delete the lock manually by following commands?
```bash
kubectl patch configmap/yurtctl-lock  -n kube-system -p '{"metadata":{"finalizers":null}}' --type=merge && kubectl delete configmap/yurtctl-lock
``` 
Also, do you happen to know why the `yurtctl convert` failed at the first?

**Comment by Fei-Guo** [comment]
We are moving towards using crd/controller to do the conversion and most of the logic in YurtCtl will be in controller. This issue will completely resolved after that. Stay tuned.

**Comment by cfw11** [comment]
> @cfw11 thanks for filing the issue. The reason `configmap/yurtctl-lock` can't be deleted is that after hitting `ctrl+c`, the `yurtctl convert` is interrupted, while the `configmap/yurtctl-lock` is not released. We will add a timeout mechanism to the lock. For now, could you try to delete the lock manually by following commands?
> 
> ```shell
> kubectl patch configmap/yurtctl-lock  -n kube-system -p '{"metadata":{"finalizers":null}}' --type=merge && kubectl delete configmap/yurtctl-lock
> ```
> 
> Also, do you happen to know why the `yurtctl convert` failed at the first?

sorry, It can't happen again.
