### ISSUE TITLE
advantages of openYurt over kubeedge?

### ISSUE THREAD

**Issue by YoshieraHuang** [alibaba/openyurt#89]
[kubeedge](https://github.com/kubeedge/kubeedge) is also an open-source edge framework. I'm choosing which one to dive in but i am confused to tell which is better.

**Comment by Fei-Guo** [comment]
It is unfair to compare two projects in a Github issue, a blog post may be a better place to discuss :).

In a nutshell, both projects attempt to resolve the edge autonomy and edge application management problems.  They all leverage Kubernetes but differ in terms of complexity, compatibility and capabilities. I'd suggest you to look at both project descriptions and we are happy to answer questions that are related with OpenYurt.

**Comment by Fei-Guo** [comment]
Let us close this one since it is not a real issue.
