### ISSUE TITLE
ask some advice: the commnication is wrong by eip 

### ISSUE THREAD

**Issue by hongfei-cloud** [alibaba/openyurt#97]
hello,
I want to ask some advice:
1、when deploying openyurt, between the edge node and cloud node , the communication is well by pulic IP
and ,the communication is wrong by EIP（elastic IP）.  the edge node is not joined to the k8s cluster by command kubeadm join。。。。。。
2、the edge node is EIP, the edge node is joined to the aliyun  Internet of things platform  ,is well by EIP. so， please consult , Is the aliyun  Internet of things platform  using the public IP or EIP （elastic IP）?

thank you very much！

**Comment by rambohe-ch** [comment]
@hongfei-cloud thank you for filing the issue.
and would you give me more information how you use openyurt.

> hello,
> I want to ask some advice:
> 1、when deploying openyurt, between the edge node and cloud node , the communication is well by pulic IP
> and ,the communication is wrong by EIP（elastic IP）. the edge node is not joined to the k8s cluster by command kubeadm join。。。。。。
the edge node can not join in the cluster, can you share your error message?

> 2、the edge node is EIP, the edge node is joined to the aliyun Internet of things platform ,is well by EIP. so， please consult , Is the aliyun Internet of things platform using the public IP or EIP （elastic IP）?
> 
> thank you very much！
what's the meaning of `the edge node is EIP`? and would you give the link of aliyun iot project, i will check it.

**Comment by hongfei-cloud** [comment]
the edge node is cloud product--cloud physical server. there is a private ip in the system.  internet network access through public IP ,the public ip is EIP（elastic IP）
阿里云也有EIP的概念，虚拟机系统里是内网IP，然后通过绑定EIP进出公网

**Comment by hongfei-cloud** [comment]
https://www.aliyun.com/product/iotedge?spm=a2c4g.750001.h2v3icoap.302.11537b13nKAbgY

**Comment by hongfei-cloud** [comment]
aliyun EIP  https://help.aliyun.com/document_detail/113775.html?spm=a2c4g.11186623.6.921.13e26f0ftBkzPX

**Comment by rambohe-ch** [comment]
@hongfei-cloud ok, in the openyurt, edge node should access public network in order to connect kube-apiserver.  and would you share your error message?

**Comment by hongfei-cloud** [comment]
我用中文描述一下：
环境：k8s v1.14.8    docker-ce 19.03.0     ubuntu18.04
cloud node and edge node 系统里是公网IP，openyurt is ok
cloud node and edge node 系统里是私有IP，通过绑定EIP，这个EIP是公网IP，来实现公网访问。原理是系统里的私有IP与此EIP做了全NAT映射关系。通过这样做测试，就不能与apiserver通信，可能是NAT的关系，node节点与apiserver通信是不是需要直通才行。因为测试环境删除了，已经改成了系统是公网IP。错误信息没法提供了。
所以我想请教，阿里云的物联网平台，云边技术也是使用openyurt吧，测试对接物联网平台时，我们的edge node系统是私有IP，通过绑定EIP，是可以与物联网平台通信的，并且加入进去。
谢谢！

**Comment by hongfei-cloud** [comment]
hello,
test environment：k8s  version : v1.14.8, docker version: docker-ce 19.03.0    system version: ubuntu18.04
The system of cloud node and edge node is public IP, openyurt is OK

The system of cloud node and edge node is a private IP. By binding EIP, this EIP is a public IP to realize public network access. The principle is that the private IP in the system has a full NAT mapping relationship with this EIP. By doing this test, the edge node can't communicate with k8s apiserver. It may be the NAT mapping between EIP and private ip. Whether the communication between node node and k8s apiserver needs to be through. Because the test environment has been deleted, the system has been changed to public IP. very sorry! The error message can't be shared

Therefore, I would like to ask that openyurt is also used for the cloud edge technology of Alibaba cloud's Internet of things platform. When testing the connection of the Internet of things platform, our edge node system is a private IP. By binding EIP, we can communicate with the IOT platform and join it.

thank you!

**Comment by rambohe-ch** [comment]
@hongfei-cloud thank you for your information.
1. if kube-apiserver is behind a EIP and edge node can access the public network, i think edge node can join in the openyurt cluster through the EIP.  now, kube-apiserver of ACK@Edge(OpenYurt commercial production of alibaba cloud) is also behind the EIP.

2. yes, some of alibaba cloud IOT productions(like [iot plantform](https://www.aliyun.com/product/iot?spm=5176.12825654.h2v3icoap.320.e9392c4aLoGfLm)) are working on the base of OpenYurt.

**Comment by hongfei-cloud** [comment]
thanks for your reply! 
During this period, I will further test and feedback the results。
